vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /pictures/article
            upload_destination: '%kernel.project_dir%/public/pictures/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
