vich_uploader:
    db_driver: orm

    mappings:
        article_picture:
            uri_prefix: /pictures/article
            upload_destination: '%kernel.project_dir%/public/pictures/article'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        user_picture:
            uri_prefix: /pictures/user
            upload_destination: '%kernel.project_dir%/public/pictures/user'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
